# base image
FROM node:14.17.0-alpine as build-stage

# set working directory
WORKDIR /case-flow-web/app

ARG REACT_APP_CASEFLOW_API_URL
ARG REACT_APP_KEYCLOAK_WEB_CLIENTID
ARG REACT_APP_KEYCLOAK_URL_REALM
ARG REACT_APP_KEYCLOAK_URL

ENV REACT_APP_CASEFLOW_API_URL ${REACT_APP_CASEFLOW_API_URL}
ENV REACT_APP_KEYCLOAK_WEB_CLIENTID ${REACT_APP_KEYCLOAK_WEB_CLIENTID}
ENV REACT_APP_KEYCLOAK_URL_REALM ${REACT_APP_KEYCLOAK_URL_REALM}
ENV REACT_APP_KEYCLOAK_URL ${REACT_APP_KEYCLOAK_URL}


# add `/app/node_modules/.bin` to $PATH
ENV PATH /case-flow-web/app/node_modules/.bin:$PATH

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

# install and cache app dependencies

COPY package-lock.json /case-flow-web/app/package-lock.json
COPY package.json /case-flow-web/app/package.json

RUN npm install --unsafe-perm --production
RUN npm install --unsafe-perm saas
#RUN npm install react-scripts@3.0.1 -g --silent
COPY . /case-flow-web/app/
RUN npm run build

FROM nginx:latest as production-stage
RUN mkdir /app
COPY --from=build-stage /case-flow-web/app/build /usr/share/nginx/html
COPY ./nginx_conf/nginx.conf /etc/nginx/nginx.conf
