/* istanbul ignore file */
const ACTION_CONSTANTS = {
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_USER_AUTHENTICATION: "SET_USER_AUTHENTICATION",
  SET_USER_TOKEN: "SET_USER_TOKEN",
  SET_USER_ROLES: "SET_USER_ROLES",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  ERROR: "ERROR",
  IS_LOADING: "IS_LOADING",
  SET_LANGUAGE: "SET_LANGUAGE",
  SET_SELECT_LANGUAGES: "SET_SELECT_LANGUAGES",
};

export default ACTION_CONSTANTS;
